### ISSUE TITLE
pi0_base model loading & UR5e bussing processor

### ISSUE THREAD

**Issue by arhanjain** [Physical-Intelligence/openpi#144]
@sergey mentioned pi0_base checkpoint should be available. i tried my best guesses at loading the model since it doesnt appear [here](https://github.com/Physical-Intelligence/openpi/blob/098d387c8e6127bdbb18d7e8bb7080dc82d9fb30/scripts/serve_policy.py#L89C1-L111C2) 

tried:
`uv run scripts/serve_policy.py policy:exported --policy.dir=s3://openpi-assets/checkpoints/pi0_base/model` 
> FileNotFoundError: [Errno 2] No such file or directory: '/mmfs1/gscratch/weirdlab/arhan/.cache/openpi/openpi-assets/checkpoints/pi0_base/model.partial'

and
`uv run scripts/serve_policy.py policy:exported --policy.dir=s3://openpi-assets/checkpoints/pi0_base/params` (found in repo, but not sufficient for model loading via `serve_policy.py` script
> `FileNotFoundError: [Errno 2] No such file or directory: '/mmfs1/gscratch/weirdlab/arhan/.cache/openpi/openpi-assets/checkpoints/pi0_base/params/graph'`

would be helpful to add base model to the default exported list. additionally, i wanted to test out the UR5e bussing task - is there a way to get the processor for that as well?

**Comment by Was-11-wendy** [comment]
@arhanjain Hello, how do you use the pi0_base model to inference with UR5 processor? I run the command 
uv run scripts/serve_policy.py --env=TBD1 policy:exported --policy.dir=s3://openpi-assets/exported/pi0_base/model --policy.processor=TBD2 
and the following error is reported. Can you help me take a look? Looking forward to your reply, thank you very much!

---------------error message--------------
Argument --env: invalid choice: 'TBD1' (choose from 'ALOHA', 'ALOHA_SIM', 'DROID', 'LIBERO') 
For full helptext, run serve_policy.py --help
